sonar.projectKey=adservice
sonar.projectName=Ad Service
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.java.binaries=build/classes
sonar.java.libraries=build/libs
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/build/**,**/out/**,**/generated/**