sonar.projectKey=recommendationservice
sonar.projectName=Recommendation Service
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.python.version=3.11
sonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**,**/dist/**