apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1-matrix-clusters
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - matrix:
        generators:
          # Dimension 1: environments from Git
          - git:
              repoURL: https://github.com/xin1lanthua123/CD-repo.git
              revision: main
              directories:
                - path: "helm/*"

          # Dimension 2: clusters (explicit, simple)
          - list:
              elements:
                - region: nvirginia
                  clusterName: in-cluster

                - region: mumbai
                  clusterName: admin@cwvj-mumbai.ap-south-1.eksctl.io
                  


          # Dimension 3: initial environment (explicit, simple)
          - list:
              elements:
                - env: dev
                - env: staging
                - env: prod

  template:
    metadata:
      name: "{{.path.basename}}-{{.env}}-{{.region}}"
    spec:
      project: default

      source:
        repoURL: https://github.com/xin1lanthua123/CD-repo.git
        targetRevision: main
        path: "{{.path.path}}"
        helm:
          releaseName: "{{.path.basename}}-{{.env}}-{{.region}}"
          valueFiles:
            - multi-env/values-{{.env}}.yaml

      destination:
        name: "{{.clusterName}}"
        namespace: "{{.path.basename}}-{{.env}}-{{.region}}-ns"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - ApplyOutOfSyncOnly=true