{{- if .Values.secret.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: {{ .Values.secret.external.targetSecretName }}

  annotations:
    argocd.argoproj.io/sync-wave: "-1"

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: {{ .Values.secret.external.secretStoreName }}
    kind: SecretStore

  target:
    name: {{ .Values.secret.external.targetSecretName }}

  data:
    - secretKey: password
      remoteRef:
        key: {{ .Values.secret.external.passwordKey }}

{{- end }}