{{- if and .Values.secret.enabled .Values.secret.fallback.enabled }}

apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}

  annotations:
    argocd.argoproj.io/sync-wave: "0"

type: Opaque

data:
  username: {{ .Values.secret.fallback.username | b64enc }}
  password: {{ .Values.secret.fallback.password | b64enc }}

{{- end }}