name: My Composite Action
description: Update image multi environment

inputs:
  IMAGE_TAG:
    description: "image_tag"
    required: true

  STARTING_PATH:
    description: "STARTING PATH"
    required: false
    default: ${{ github.workspace }}

  IDENTIFIER_COMMENT:
    description: "IDENTIFIER COMMENT"
    required: true
secrets:
  GITOPS_TOKEN:
    description: " Gitops Repo Token"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Checkout GitOps Repo
      uses: actions/checkout@v4
      with:
        repository: xin1lanthua123/CD-repo
        token: ${{ inputs.GITOPS_TOKEN }}
        path: gitops


    - name: Update YAML files 
      shell: bash
      run: |
        set -euo pipefail

        IMAGE_TAG="${{ inputs.IMAGE_TAG }}"
        STARTING_PATH="${{ inputs.STARTING_PATH }}"
        IDENTIFIER_COMMENT="${{ inputs.IDENTIFIER_COMMENT }}"

        if [ -z "$IMAGE_TAG" ]; then
          echo "IMAGE_TAG is required"
          exit 1
        fi

        echo "IMAGE_TAG=$IMAGE_TAG"
        echo "STARTING_PATH=$STARTING_PATH"
        echo "IDENTIFIER_COMMENT=$IDENTIFIER_COMMENT"

        find "$STARTING_PATH" -type f \( -name "*.yaml" -o -name "*.yml" \) \
        -exec grep -l "$IDENTIFIER_COMMENT" {} \; | while read -r file; do

            echo "Processing $file"
            echo "Updating $file"

            # Pattern 1:
            # image: nginx:1.0.0 # DEV_IMAGE_TAG (used for Kubernetes manifest)
            sed -i "s|\(\s*image:\s*\).*${IDENTIFIER_COMMENT}|\1${IMAGE_TAG} ${IDENTIFIER_COMMENT}|g" "$file"
            
            # Pattern 2:
            # tag: nginx:1.0.0 # DEV_IMAGE_TAG (used for HELM manifest )
            sed -i "s|\(\s*tag:\s*\).*${IDENTIFIER_COMMENT}|\1${IMAGE_TAG} ${IDENTIFIER_COMMENT}|g" "$file"

            echo "$file has been updated successfully"

          fi

        done

    - name: Commit
      run: |
          cd gitops

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git checkout -b  ci/feature/${{ inputs.services }} -${{ env.IMAGE_TAG }}

          git add .
          git commit -m "chore(${{ inputs.services }}): update image ${{ env.IMAGE_TAG }}"

          git push origin HEAD
    
    - name: Create PR
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ inputs.GITOPS_TOKEN }}
        path: gitops
        branch: ci/feature/${{ inputs.services }}-${{ env.IMAGE_TAG }}
        base: main
        title: |
          Promote ${{ inputs.services }} -> ${{ env.IMAGE_TAG }}
        body: |
          Generated by CI

          Service: ${{ inputs.services }}
          Image: ${{ env.IMAGE_TAG }}