sonar.projectKey=paymentservice
sonar.projectName=Payment Service
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.exclusion=**/node-modules/**,**/dist/**,**/build/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

