name: demo CI

on:
  workflow_dispatch:
    inputs:
        action:
            description: "Terraform action"
            required: true
            default: "apply"
            type: choice
            options:
            - apply

jobs:
  echo-ci:
    name: Echo CI/CD Trigger Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: xin1lanthua123/CD-repo
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops
          
    #   - name: Print workflow info
    #     run: |
    #       set -euo pipefail

    #       cd gitops

    #       git config user.name "quanldl"
    #       git config user.email "ldlq2005@gmail.com"

    #       branch="ci/feature/payment"
    #       git checkout -b "$branch" || git checkout "$branch"
    #       git add .
    #       git commit -m "chore: update $branch branch" || echo "No changes to commit"
    #       git push origin $branch

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops
          branch: ci/feature/payment
          base: main
          body: |
            Generated by CI repo

            Service: payment
            Image: Image Tag

      - name: Echo success
        run: |
          echo "Workflow is running successfully"
          echo "CI trigger OK"
          echo "CD repo trigger can now be tested"