name: Update Image Multi Environment

on:
  workflow_call:
    inputs:
      ENV:
        description: "environment"
        required: true
        type: string
      IMAGE_TAG:
        description: "image tag"
        required: true
        type: string

      STARTING_PATH:
        description: "starting path"
        required: false
        type: string
        default: "."

      IDENTIFIER_COMMENT:
        description: "identifier comment"
        required: true
        type: string

      SERVICES:
        description: "service name"
        required: false
        type: string

    secrets:
      GITOPS_TOKEN:
        description: "GITOPS REPO TOKEN"
        required: true

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: xin1lanthua123/CD-repo
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update YAML files
        shell: bash
        run: |
          set -euo pipefail

          IMAGE_TAG="${{ inputs.IMAGE_TAG }}"
          STARTING_PATH="${{ inputs.STARTING_PATH }}"
          IDENTIFIER_COMMENT="${{ inputs.IDENTIFIER_COMMENT }}"

          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "STARTING_PATH=$STARTING_PATH"
          echo "IDENTIFIER_COMMENT=$IDENTIFIER_COMMENT"

          find "$STARTING_PATH" -type f \( -name "*.yaml" -o -name "*.yml" \) \
            -exec grep -l "$IDENTIFIER_COMMENT" {} \; | while read -r file; do

              echo "Processing $file"

              # Pattern 1:
              # image: nginx:1.0.0 # DEV_IMAGE_TAG (used for Kubernetes manifest)
                  sed -i "s|\(\s*image:\s*\).*${IDENTIFIER_COMMENT}|\1${IMAGE_TAG} ${IDENTIFIER_COMMENT}|g" "$file"
             
              
              # Pattern 2:
              # tag: nginx:1.0.0 # DEV_IMAGE_TAG (used for HELM manifest )
                sed -i "s|\(\s*tag:\s*\).*${IDENTIFIER_COMMENT}|\1${IMAGE_TAG} ${IDENTIFIER_COMMENT}|g" "$file"

              echo "$file updated"
          done

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops
          branch: ci/feature/${{ inputs.SERVICES }}-${{ inputs.ENV }}-${{ inputs.IMAGE_TAG }}
          base: main
          title: "Promote ${{ inputs.SERVICES }} -> ${{ inputs.IMAGE_TAG }}"
          delete-branch: true
          commit-message: |
            chore(${{
              inputs.ENV
            }}): update ${{ inputs.SERVICES }} image -> ${{ inputs.IMAGE_TAG }}
          body: |
            Generated by CI repo

            Service: ${{ inputs.SERVICES }}
            Image: ${{ inputs.IMAGE_TAG }}
            Env: ${{ inputs.ENV }}

      - name: Auto merge for DEV environment
        shell: bash
        if: inputs.ENV == 'dev'
        run: |
          gh pr merge --auto --squash 
      
          
      