name: Reusable workflow CICD pipeline
on: 
    workflow_call:
      inputs:
        action:
            description: "Terraform action"
            required: true
            default: "apply-ENV"
            type: string
        env:
            description: "environment (prod or dev)"
            required: true
            default: "dev"
            type: string
        aws_region:
            description: "AWS region"
            required: true
            type: string


      
      secrets:
        AWS_ACCESS_KEY_ID:
          required: true
        AWS_SECRET_ACCESS_KEY:
          required: true
jobs:
    terraform-bootstrap:
        runs-on: ubuntu-latest
        if: inputs.action == 'bootstrap'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Install Terragrunt and OpenTofu
              uses: gruntwork-io/terragrunt-action@v3
              with:
                    tg_version: '0.82.2'
                    tofu_version: '1.10.1'

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ inputs.aws_region }}
            - name: Plan terraform bootstrap using terragrunt
              working-directory: infra/terragrunt/bootstrap/local
              shell: bash
              run: |
                set -euo pipefail
                terragrunt plan --terragrunt-non-interactive

            - name: Apply terraform bootstrap using terragrunt
              working-directory: infra/terragrunt/bootstrap/local
              shell: bash
              run: |
                set -euo pipefail
                trap 'echo "Apply failed, destroying resources..."; terragrunt destroy --auto-approve --terragrunt-non-interactive' ERR
                terragrunt apply --auto-approve --terragrunt-non-interactive
                
                # terragrunt init -reconfigure

                # terragrunt output -json > bootstrap.json

            # mv bootstrap.json $GITHUB_WORKSPACE/bootstrap.json

            # - name: Extract output from local boostrap state
            #   working-directory: infra/terragrunt/bootstrap/local
            #   shell: bash
            #   run: |
            #     terragrunt init -reconfigure
            #     terragrunt output -json > bootstrap.json

            # - name: Artifact Upload
            #   uses: actions/upload-artifact@v4
            #   with:
            #     name: bootstrap-state
            #     path: infra/terragrunt/bootstrap/local/bootstrap.json

            - name: set up config for state migration
              working-directory: infra/terragrunt/bootstrap/local
              shell: bash
              run: |
                chmod +x remote_state.sh 
                ./remote_state.sh

            - name: Migrate local state to remote state S3
              working-directory: infra/terragrunt/bootstrap/local
              shell: bash
              run: |
                terragrunt init -migrate-state -force-copy -terragrunt-non-interactive 

                # terragrunt destroy -auto-approve --terragrunt-non-interactive
    apply-env:
        runs-on: ubuntu-latest
        if: inputs.action == 'apply-ENV'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup jq
              uses: dcarbone/install-jq-action@v2

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Install Terragrunt and OpenTofu
              uses: gruntwork-io/terragrunt-action@v3
              with:
                    tg_version: '0.82.2'
                    tofu_version: '1.10.1'

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ inputs.aws_region }}

            # - name: Download Artifact of boostrap state from the job 1
            #   uses: actions/download-artifact@v4
            #   with:
            #     name: bootstrap-state

            # - name: Update the root remote state config
            #   working-directory: infra/terragrunt/bootstrap/local
            #   shell: bash
            #   run: |
            #       set -euo pipefail
            #       chmod +x json_state.sh
            #       ./json_state.sh

            - name: Plan terraform infra using terragrunt
              shell: bash
              working-directory: infra/terragrunt/us-east-1/${{ inputs.env }}
              run: |
                terragrunt run-all plan --terragrunt-non-interactive
            

            - name: Apply terraform infra using terragrunt
              working-directory: infra/terragrunt/us-east-1/${{ inputs.env }}
              shell: bash
              run: |
                set -euo pipefail
                trap 'echo "Apply failed, destroying resources..."; terragrunt destroy --auto-approve --terragrunt-non-interactive' ERR
                terragrunt run-all apply -auto-approve --terragrunt-non-interactive
    destroy-env:
        runs-on: ubuntu-latest
        if: inputs.action == 'destroy-ENV'
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Install Terragrunt and OpenTofu
              uses: gruntwork-io/terragrunt-action@v3
              with:
                    tg_version: '0.82.2'
                    tofu_version: '1.10.1'

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ inputs.aws_region }}
            # - name: Download Artifact of boostrap state from the job 1
            #   uses: actions/download-artifact@v4
            #   with:
            #     name: bootstrap-state

            # - name: Update the root remote state config
            #   working-directory: infra/terragrunt/bootstrap/local
            #   shell: bash
            #   run: |
            #       set -euo pipefail
            #       chmod +x json_state.sh
            #       ./json_state.sh

            - name: Destroy terraform infra using terragrunt
              working-directory: infra/terragrunt/us-east-1/${{ inputs.env }}
              shell: bash
              run: |
                set -euo pipefail
                terragrunt run-all destroy -auto-approve --terragrunt-non-interactive
            
            # - name: Reupdate terraform bootstrap state using bash script
            #   working-directory: infra/terragrunt/bootstrap/local
            #   shell: bash
            #   run: |
            #     set -euo pipefail
            #     chmod +x back_to_localstate.sh
            #     ./back_to_localstate.sh

            - name: Migrate backend s3 back to local
              working-directory: infra/terragrunt/bootstrap/local
              shell: bash
              run: |
                set -euo pipefail
                terragrunt init -migrate-state -force-copy -terragrunt-non-interactive 

            - name: Destroy terraform bootstrap using terragrunt
              working-directory: infra/terragrunt/bootstrap/local
              shell: bash
              run: |
                
                terragrunt destroy -auto-approve --terragrunt-non-interactive
            
            - name: destroy all s3 bucket versioning
              working-directory: infra/terragrunt
              shell: bash
              run: |
                set -euo pipefail
                chmod +x delete-s3.sh
                ./delete-s3.sh

            
